name: Build Custom OpenWrt Firmware (WHW03 V2)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download OpenWrt ImageBuilder 24.10.0
        run: |
          wget https://downloads.openwrt.org/releases/24.10.0/targets/ipq40xx/generic/openwrt-imagebuilder-24.10.0-ipq40xx-generic.Linux-x86_64.tar.xz
          tar -xf openwrt-imagebuilder-*.tar.xz
          mv openwrt-imagebuilder-* imagebuilder

      - name: Copy custom files
        run: |
