name: Build Custom OpenWrt Firmware (WHW03 V2)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zstd xz-utils

      - name: Download OpenWrt ImageBuilder 24.10.0-rc4
        run: |
           wget https://downloads.openwrt.org/releases/24.10.0-rc4/targets/ipq40xx/generic/openwrt-imagebuilder-24.10.0-rc4-ipq40xx-generic.Linux-x86_64.tar.zst
           unzstd openwrt-imagebuilder-*.tar.zst
           tar -xf openwrt-imagebuilder-*.tar
           mv openwrt-imagebuilder-24.10.0-rc4-ipq40xx-generic.Linux-x86_64 imagebuilder

      - name: Copy custom files
        run: |
          mkdir -p imagebuilder/files
          cp -r files/* imagebuilder/files/

      - name: Build firmware
        run: |
          cd imagebuilder
          make image PROFILE="linksys_whw03-v2" \
          PACKAGES="luci luci-compat luci-app-passwall luci-app-passwall2 luci-app-openvpn luci-app-wireguard luci-app-wol luci-app-openconnect luci-app-amnezia luci-theme-bootstrap" \
          FILES=files/


      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: imagebuilder/bin/targets/ipq40xx/generic/*.bin
