name: Customize OpenWrt Firmware

on:
  workflow_dispatch:

jobs:
  customize-firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y squashfs-tools binwalk wget xz-utils

      - name: Download raw OpenWrt firmware
        run: |
          wget -O openwrt-whw03v2.bin https://downloads.openwrt.org/releases/24.10.3/targets/ipq40xx/generic/openwrt-24.10.3-ipq40xx-generic-linksys_whw03v2-squashfs-sysupgrade.bin

      - name: Extract firmware
        run: |
          mkdir rootfs
          mkdir mnt
          # extract squashfs from sysupgrade
          binwalk -e openwrt-whw03v2.bin
          # locate squashfs file (معمولاً _squashfs.bin)
          SQFS=$(find _openwrt-whw03v2.bin.extracted -name "*squashfs.bin" | head -n1)
          sudo mount -o loop $SQFS mnt

      - name: Apply custom files
        run: |
          sudo cp -r files/* mnt/
          # اگر نیاز به مجوز فایل‌ها است:
          sudo chown -R root:root mnt/

      - name: Repack firmware
        run: |
          # unmount
          sudo umount mnt
          # rebuild squashfs
          mksquashfs mnt rootfs-custom.squashfs -comp xz
          # merge با header sysupgrade (نیاز به اسکریپت پیشرفته برای مطابقت با sysupgrade)
          # ساده ترین روش: فایل squashfs جدید را جایگزین squashfs قدیمی با binwalk و dd
          echo "⚠️ مرحله merge squashfs با header نیاز به اسکریپت دقیق دارد"

      - name: Upload custom firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: rootfs-custom.squashfs
